/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.stefankoppier.oasdiff

import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import java.io.File.separator
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertTrue

class OasdiffPluginFunctionalTest {
    @get:Rule val tempFolder = TemporaryFolder()

    lateinit var runner: GradleRunner

    private val projectDir
        get() = tempFolder.root

    private val buildFile
        get() = projectDir.resolve("build.gradle")

    @BeforeTest
    fun before() {
        buildFile.writeText(
            """
                plugins {
                    id("io.github.stefankoppier.oasdiff")
                }
            """.trimIndent()
        )

        runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withProjectDir(projectDir)
    }

    @Test
    fun `can run oasdiffInstall task`() {
        runner.withArguments("oasdiffInstall")
        runner.build()

        projectDir.resolve(".gradle${separator}oasdiff").run {
            assertTrue("folder '$path' does not exist") { exists() }
            this.resolve("1.3.21").run {
                assertTrue("folder '$path' does not exist") { exists() }
                this.resolve("oasdiff.exe").run {
                    assertTrue("file '$path' does not exist") { exists() }
                }
            }
        }
    }
}
