name: Build

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

#      - name: Build Windows
#        uses: ./.github/workflows/build-windows.yml

      - name: Build Linux
        uses: ./.github/workflows/build-linux.yml