name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Increment
        required: true
        options:
          - Patch
          - Minor
          - Major

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get current version
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Get next versions
        id: nexttag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Determine release version
        id: nextversion
        run: |
          case "${{ inputs.increment }}" in
            Patch) 
              echo "version=${{ steps.nexttag.outputs.patch }}" >> $GITHUB_OUTPUT
              ;;
            Minor) 
              echo "version=${{ steps.nexttag.outputs.minor }}" >> $GITHUB_OUTPUT
              ;;
            Major) 
              echo "version=${{ steps.nexttag.outputs.major }}" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Update project version
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: ./gradle.properties
          property: 'version'
          value: ${{ steps.nextversion.outputs.version }}

      - name: Commit, push and tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated project version"
          git push
          git tag $VERSION
          git push origin $VERSION
        env:
          VERSION: ${{ steps.nextversion.outputs.version }}

      - name: Github release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugins -Dgradle.publish.key=${{ secrets.PUBLISH_KEY }} -Dgradle.publish.secret=${{ secrets.PUBLISH_SECRET }}
          gradle-version: wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}