name: Renovate

#on:
#  schedule:
#    # The "*" (#42, asterisk) character has special semantics in YAML, so this
#    # string has to be quoted.
#    - cron: '0/15 * * * *'

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/config/renovate.js
