name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Renovate
        uses: renovatebot/github-action@v36.0.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/config/renovate.js
